FROM gradle
COPY ./ ./

ARG DATABASE_USER
ARG DATABASE_PASS
ARG DATABASE_NAME
ARG DATABASE_URL
ARG DATABASE_PORT
ARG ADMIN_USER
ARG ADMIN_PASS

# Set the environment variables
ENV DB_USER=$DATABASE_USER
ENV DB_PASS=$DATABASE_PASS
ENV DB_NAME=$DATABASE_NAME
ENV DB_URL=$DATABASE_URL
ENV DB_PORT=$DATABASE_PORT
ENV ADMIN_USERNAME=$ADMIN_USER
ENV ADMIN_PASSWORD=$ADMIN_PASS
ENV SPRING_PROFILES_ACTIVE=prod

RUN ./gradlew clean build
EXPOSE 8888
ENTRYPOINT ["java", "-jar", "build/libs/giftcertificate-0.0.1.jar"]
